name: Airtable Human Services API
url: http://airtable.portal.adopta.agency/

author:
  name: 'Kin Lane'
  email: 'info@apievangelist.com'
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

github_org: human-services
github_repo: airtable

# blog stuff
permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 150
paginate_path: "/blog/page:num"
